version: '3.8'

services:
  tests:
    build: .
    env_file:
      - .env
    command: pytest -v -s
    volumes:
      - ./app:/app/config/app
      - ./tests:/app/tests

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app/config/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - db.env

volumes:
  postgres_data:
